services:
  - name: chess-ai-backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend server:app --workers 2 --threads 2 --timeout 120 --keep-alive 5 --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - name: chess-ai-frontend
    type: static
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: chess-web/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://chess-ai-backend.onrender.com"
        plan: free
        
